In [2]:
#NumPy is all about arrays 

In [4]:
#arrays are a list of numbers ; scalars, vectors, and matrix are a part of them( only the dimentions change between the 3)


In [6]:
#arrays can have any number of dimentions, including zero( a scalar)
#arrays are typed
#arrays are dense. each element of an array exists and has the same type 
#arrys are faster than python lists( consume less memory) 
# can only combine arrays of the same shape 
import numpy as np 
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a.ndim, a.shape, a.dtype)

2 (2, 3) float32


In [10]:
# 6 dimentional array
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]], ndmin=6)
c

array([[[[[[1, 2, 3],
           [4, 5, 6]],

          [[1, 2, 3],
           [4, 5, 6]]]]]])

In [12]:
a = a.reshape(3,2)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

In [14]:
a = a.ravel()
a

array([1., 2., 3., 4., 5., 6.], dtype=float32)